name: qareeb_dash

description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#GET
#api/services/app/InstitutionBusTripsService/

version: 1.0.6+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: html
  universal_html:
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: any
  http: any
  easy_sidemenu: ^0.4.1+1
  #  responsive_sizer: ^3.1.1
  shared_preferences: any
  bloc: ^8.1.2
  flutter_admin_scaffold: ^1.2.0
  lottie: any
  flutter_svg: any
  cached_network_image: any
  flutter_screenutil: any
  #  animated_snack_bar: ^0.3.0
  pinput: ^2.2.21
  syncfusion_flutter_datepicker: ^22.1.39
  flutter_rating_bar: ^4.0.1
  image_picker: any
  syncfusion_flutter_core: ^22.1.37
  carousel_slider:
  flutter_map_animations: ^0.3.0
#  syncfusion_flutter_charts: ^22.1.37
#  responsive_table: ^0.2.0+2
  syncfusion_flutter_datagrid: ^22.1.37
  #  flutter_osm_plugin: any
  url_launcher: any
  qr_flutter: ^4.1.0
  screenshot: ^2.1.0
  latlong2: any
  share_plus: ^7.1.0
  flutter_map: 4.0.0
  logger: ^1.1.0
  dropdown_button2: ^2.3.9
  flutter_keyboard_visibility: ^5.4.0
  firebase_core: any
  firebase_messaging: any
  geolocator: ^9.0.2
  excel: ^2.1.0

  package_info_plus: ^4.1.0
  #  hive: ^2.2.3
  #  flutter_background_service: ^3.0.1
  intl:
  collection:
  path_provider: any
  path: any
  flutter_local_notifications: ^14.1.0
  sqflite: any
  #  flutter_typeahead: ^4.3.6
  #  awesome_dialog: ^3.0.2
  webview_flutter: any
  #  flutter_map_animated_marker: ^1.0.1
  google_polyline_algorithm: ^3.1.0
  shimmer_animation: ^2.1.0+1
  #  flutter_cache_manager: ^3.3.0
  url_strategy:
  group_button: ^5.2.2
  go_router: ^6.5.8
#  easy_autocomplete: ^1.6.0
  webview_flutter_android: ^3.4.5
  webview_flutter_wkwebview: ^3.2.4
  multi_select_flutter: ^4.1.3
#  flutter_cupertino_datetime_picker: ^3.0.0
#  location_permissions:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lotties/
    - assets/sounds/
    - assets/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
    - family: cairoBold
      fonts:
        - asset: assets/fonts/cairo_bold.ttf
    - family: cairoSemiBold
      fonts:
        - asset: assets/fonts/cairo_semi_bold.ttf


