name: qareeb_dash
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: html

  qareeb_models:
    git:
      url: https://github.com/saedAlHanash/qareeb_models


  map_package:
    git:
      url: https://github.com/saedAlHanash/map_qareeb
      ref: google+_map_test

  excel: ^2.1.0
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: any
  http: any
  easy_sidemenu: ^0.4.1+1
  #  responsive_sizer: ^3.1.1
  shared_preferences: any
  #  bloc: ^8.1.0
  flutter_admin_scaffold: ^1.2.0
  lottie: any
  flutter_svg: any
  cached_network_image: any
  flutter_screenutil: any
  #  animated_snack_bar: ^0.3.0
  pinput: ^2.2.21
  syncfusion_flutter_datepicker: ^22.1.39
  flutter_rating_bar: ^4.0.1
  image_picker: any
  syncfusion_flutter_core: ^22.1.37
  carousel_slider: any
  #  syncfusion_flutter_charts: ^22.1.37
  #  responsive_table: ^0.2.0+2
  syncfusion_flutter_datagrid: ^22.1.37
  #  flutter_osm_plugin: any
  url_launcher: any
#  latlong2: any
#  flutter_map: 4.0.0
  google_maps_flutter: ^2.5.0
  logger: ^1.1.0
  dropdown_button2: ^2.3.9
  flutter_keyboard_visibility: ^5.4.0
  firebase_core: any
  firebase_messaging: any
  geolocator: ^9.0.2
  #  hive: ^2.2.3
  #  flutter_background_service: ^3.0.1
  intl:
  collection:
  path_provider: any
  path: any
  flutter_local_notifications: ^14.1.0
  sqflite: any
  #  flutter_typeahead: ^4.3.6
  #  awesome_dialog: ^3.0.2
  webview_flutter: any
  #  flutter_map_animated_marker: ^1.0.1
  google_polyline_algorithm: ^3.1.0
  shimmer_animation: ^2.1.0+1
  #  flutter_cache_manager: ^3.3.0
  url_strategy:
  group_button: ^5.2.2
  go_router: ^6.5.8
  #  easy_autocomplete: ^1.6.0
  webview_flutter_android: ^3.4.5
  webview_flutter_wkwebview: ^3.2.4
#  flutter_cupertino_datetime_picker: ^3.0.0
#  location_permissions:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lotties/
    - assets/sounds/
    - assets/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
    - family: cairoBold
      fonts:
        - asset: assets/fonts/cairo_bold.ttf
    - family: cairoSemiBold
      fonts:
        - asset: assets/fonts/cairo_semi_bold.ttf


